import Link from 'next/link'

const modules = [
  ['Requests','Create, edit, search and execute factory requests.','/requests'],
  ['Runs','Track pipeline stages, logs, artifacts and failures.','/runs'],
  ['Projects','Manage generated projects and validation state.','/projects'],
  ['Repairs','Review bounded self-healing actions and history.','/repairs'],
  ['Validation','Inspect release gates before go-live.','/validation'],
  ['Audit','Follow important factory events.','/audit'],
]

const stages = ['REQUEST','PLANNER','GENERATOR','TEST','SELF-HEAL','VALIDATOR','GO-LIVE']

export default function Home(){return <main className="factory-shell">
  <aside className="sidebar"><div className="brand-mark"><span>AK</span><div><strong>AK VISIO</strong><small>SOFTWARE FACTORY V2</small></div></div><nav><p>CONTROL CENTER</p><Link className="nav-active" href="/">Overview</Link><Link href="/requests">Requests</Link><Link href="/runs">Runs</Link><p>DELIVERY</p><Link href="/projects">Projects</Link><Link href="/repairs">Repairs</Link><Link href="/validation">Validation</Link><p>GOVERNANCE</p><Link href="/audit">Audit trail</Link></nav><div className="sidebar-footer"><i/> Factory online<div>V2 · Isolated environment</div></div></aside>
  <section className="workspace"><header className="workspace-head"><div><span className="kicker">SOFTWARE FACTORY CONTROL PLANE</span><h1>Operations overview</h1></div><div className="head-actions"><span className="system-status"><i/> Operational</span><Link href="/requests" className="create-btn">+ New request</Link></div></header>
  <section className="hero-panel"><div className="hero-copy"><span className="section-label">CURRENT PIPELINE</span><h2>Build. Test. Heal.<br/><em>Validate. Ship.</em></h2><p>One observable workflow from request intake to production release, with every state and recovery path visible.</p><div className="hero-meta"><span>RUN-2026-0913-014</span><b>Generation in progress</b></div></div><div className="pipeline-visual">{stages.map((x,i)=><div className={'stage '+(i<2?'done':i===2?'active':'')} key={x}><div className="stage-node">{i<2?'✓':String(i+1).padStart(2,'0')}</div><strong>{x}</strong></div>)}</div></section>
  <section className="metrics"><article><span>ACTIVE RUNS</span><strong>04</strong><small>2 executing · 2 queued</small></article><article><span>GENERATED PROJECTS</span><strong>18</strong><small>16 validated</small></article><article><span>REPAIRS TODAY</span><strong>03</strong><small>100% re-tested</small></article><article><span>RELEASE READINESS</span><strong>96<span>%</span></strong><small>All critical gates clear</small></article></section>
  <section className="content-grid"><div className="panel"><div className="panel-head"><div><span className="section-label">LIVE ACTIVITY</span><h3>Factory events</h3></div><Link href="/audit">View audit →</Link></div><div className="events"><div><i className="success"/><div><strong>Validation gate passed</strong><p>Project V2-018 · production checks complete</p></div><time>2m</time></div><div><i className="active"/><div><strong>Generation running</strong><p>RUN-2026-0913-014 · 68% complete</p></div><time>now</time></div><div><i className="success"/><div><strong>Self-healing completed</strong><p>RUN-2026-0913-011 · 1 repair applied</p></div><time>11m</time></div></div></div><div className="panel"><div className="panel-head"><div><span className="section-label">GO-LIVE GATE</span><h3>Release readiness</h3></div><Link href="/validation">Inspect →</Link></div><div className="readiness-score"><strong>96</strong><span>/100</span><b>READY</b></div><div className="gate-list"><span>Build integrity <b>PASS</b></span><span>Test suite <b>PASS</b></span><span>Security gates <b>PASS</b></span><span>Audit completeness <b>PASS</b></span></div></div></section>
  <section className="modules"><span className="section-label">FACTORY MODULES</span><div className="module-grid">{modules.map(([title,desc,href])=><Link className="module" href={href} key={title}><div><span>{title}</span><b>↗</b></div><p>{desc}</p></Link>)}</div></section>
  <footer><span>AK VISIO Software Factory V2</span><span>Dedicated Supabase project · Strictly isolated from ADTRAN Realindo</span></footer></section></main>}
