import { createHash } from 'node:crypto'
import type { DeploymentEvidence } from './deployment.ts'
import type { DeploymentLifecycleState } from './deployment-state.ts'
export const MONITORING_ENGINE_VERSION = '1.0.0'
export type DeploymentHealth = 'healthy' | 'degraded' | 'unhealthy'
export type DeploymentMonitorInput = { evidence: DeploymentEvidence; state: DeploymentLifecycleState; checkedAt: string; maxAgeSeconds: number }
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex')
export function assessDeploymentHealth(input:DeploymentMonitorInput){const age=Math.max(0,Math.floor((Date.parse(input.checkedAt)-Date.parse(input.evidence.completedAt))/1000));const healthy=input.evidence.action==='deploy'&&input.evidence.status==='succeeded'&&input.state==='verified'&&input.evidence.verificationStatus==='passed'&&input.evidence.providerReference!=='unavailable'&&age<=input.maxAgeSeconds;const degraded=!healthy&&input.evidence.status==='succeeded'&&input.state!=='failed'&&age<=input.maxAgeSeconds;const health:DeploymentHealth=healthy?'healthy':degraded?'degraded':'unhealthy';const reason=health==='healthy'?'deployment_verified_and_fresh':input.evidence.status!=='succeeded'?'deployment_failed':input.state==='failed'?'deployment_state_failed':input.evidence.verificationStatus!=='passed'?'deployment_verification_not_passed':input.evidence.providerReference==='unavailable'?'provider_reference_missing':'deployment_stale';return{health,reason,ageSeconds:age,evidenceHash:hash({deploymentId:input.evidence.deploymentId,health,reason,checkedAt:input.checkedAt,ageSeconds:age}),monitoringEngineVersion:MONITORING_ENGINE_VERSION}}
export function assertAutonomousRecoveryEligible(input:{current:DeploymentEvidence;currentState:DeploymentLifecycleState;target:DeploymentEvidence;targetState:DeploymentLifecycleState;health:DeploymentHealth}){if(input.health!=='unhealthy')throw new Error('recovery_requires_unhealthy_deployment');if(input.current.action!=='deploy'||input.current.status!=='succeeded')throw new Error('recovery_current_deployment_invalid');if(input.target.action!=='deploy'||input.target.status!=='succeeded')throw new Error('recovery_target_invalid');if(input.currentState==='failed'||input.current.verificationStatus!=='passed')throw new Error('recovery_current_lineage_invalid');if(input.targetState!=='verified'&&input.targetState!=='promoted')throw new Error('recovery_target_not_verified');if(input.target.verificationStatus!=='passed'||!input.target.providerReference||input.target.providerReference==='unavailable')throw new Error('recovery_target_verification_required');if(input.current.ownerId!==input.target.ownerId||input.current.organizationId!==input.target.organizationId||input.current.environment!==input.target.environment||input.current.provider!==input.target.provider)throw new Error('recovery_scope_mismatch');if(input.target.deploymentId===input.current.deploymentId)throw new Error('recovery_target_must_be_previous_deployment')}
export function createRecoveryDecision(input:Parameters<typeof assertAutonomousRecoveryEligible>[0]){assertAutonomousRecoveryEligible(input);const evidenceHash=hash({current:input.current.deploymentId,target:input.target.deploymentId,health:input.health});return{decisionId:'recovery-'+evidenceHash.slice(0,24),decision:'eligible' as const,evidenceHash}}
